// ═══ 成就系统 ═══

export interface Achievement {
  key: string;
  name: string;
  desc: string;
  trigger: string;          // 触发条件描述
  reward: { type: "card" | "tokens"; cardId?: string; amount?: number; tokens?: number };
  hidden: boolean;          // 隐藏成就（解锁前不显示触发条件与奖励）
  status: "testing" | "live"; // 未测试 / 已上线
}

export const ACHIEVEMENTS: Achievement[] = [
  {
    key: "passion",
    name: "受难曲",
    desc: "卡片合成首次失败",
    trigger: "卡片合成首次失败",
    reward: { type: "card", cardId: "blue_邓紫棋_受难曲", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "dont-go-home",
    name: "不想回家",
    desc: "于18:00-19:00进入网站",
    trigger: "每日18:00-19:00时间段打开网页",
    reward: { type: "card", cardId: "gold_邓紫棋_不想回家", tokens: 10000 },
    hidden: true,
    status: "testing",
  },
  {
    key: "only-you-and-me",
    name: "只有我和你的地方",
    desc: "首次登录暗号",
    trigger: "首次输入暗号绑定卡牌存档",
    reward: { type: "card", cardId: "blue_邓紫棋_只有我和你的地方", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "boy-and-sea",
    name: "少年与海",
    desc: "待定·2077联动",
    trigger: "待定·2077模块",
    reward: { type: "card", cardId: "blue_邓紫棋_少年与海", tokens: 10000 },
    hidden: false,
    status: "testing",
  },
  {
    key: "old-man-and-sea",
    name: "老人与海",
    desc: "待定·2077联动",
    trigger: "待定·2077模块",
    reward: { type: "card", cardId: "blue_邓紫棋_老人与海", tokens: 10000 },
    hidden: false,
    status: "testing",
  },
  {
    key: "ice-age",
    name: "冰河时代",
    desc: "解锁所有弗雷尔卓德英雄白卡",
    trigger: "集齐所有弗雷尔卓德地区英雄的白卡",
    reward: { type: "card", cardId: "blue_邓紫棋_冰河时代", tokens: 10000 },
    hidden: false,
    status: "testing",
  },
  {
    key: "find-you",
    name: "FIND YOU",
    desc: "创建一个名为《K/DA》的时空奇旅相册",
    trigger: "COA纪念册中创建分类名为K/DA",
    reward: { type: "card", cardId: "blue_邓紫棋_Find You", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "gloria",
    name: "GLORIA",
    desc: "解锁一张任意稀有度邓紫棋卡片",
    trigger: "获得任意gem类型卡片（白/蓝/金/终极均可）",
    reward: { type: "card", cardId: "blue_邓紫棋_Gloria", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "pause-the-world",
    name: "让世界暂停一分钟",
    desc: "首次上传照片至定格时光",
    trigger: "首次在时间定格中上传照片",
    reward: { type: "card", cardId: "blue_邓紫棋_让世界暂停一分钟", tokens: 10000 },
    hidden: false,
    status: "testing",
  },
  {
    key: "end-of-night",
    name: "夜的尽头",
    desc: "2077相关待定",
    trigger: "待定·2077模块",
    reward: { type: "card", cardId: "gold_邓紫棋_夜的尽头", tokens: 10000 },
    hidden: true,
    status: "testing",
  },
  {
    key: "centrifugal",
    name: "离心力",
    desc: "污渍+标准一天内总计猜错15次",
    trigger: "同一日内标准+污渍模式累计猜错15次",
    reward: { type: "card", cardId: "gold_邓紫棋_离心力", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "sky-no-limit",
    name: "天空没有极限",
    desc: "创建5个（含驿站）奇旅相册",
    trigger: "时空奇旅分类数≥5",
    reward: { type: "card", cardId: "gold_邓紫棋_天空没有极限", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "revelation",
    name: "启示录",
    desc: "解锁所有启示录专辑歌曲卡片",
    trigger: "集齐所有gem类型卡片（启示录专辑曲目）",
    reward: { type: "card", cardId: "max_邓紫棋_启示录", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "not-first-leave",
    name: "你不是第一个离开的人",
    desc: "距离上次登录超过24小时",
    trigger: "再次登录时距上次超过24小时",
    reward: { type: "card", cardId: "blue_邓紫棋_你不是第一个离开的人", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "hell-1",
    name: "HELL·1",
    desc: "首次使用崔斯特的赌约赌中红牌",
    trigger: "崔斯特的赌约抽中红牌(-200币)",
    reward: { type: "card", cardId: "blue_邓紫棋_Hell 白", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "hell-2",
    name: "HELL·2",
    desc: "首次使用崔斯特的赌约赌中金牌",
    trigger: "崔斯特的赌约抽中金牌",
    reward: { type: "card", cardId: "blue_邓紫棋_Hell 黑", tokens: 10000 },
    hidden: false,
    status: "live",
  },
  {
    key: "basketball",
    name: "篮球可不是一个人的游戏",
    desc: "集齐勒布朗詹姆斯与文班亚马",
    trigger: "获得勒布朗詹姆斯 + 文班亚马",
    reward: { type: "card", cardId: "max_NBA_凯尔科尔沃", tokens: 10000 },
    hidden: true,
    status: "live",
  },
  {
    key: "new-continent",
    name: "新大陆",
    desc: "首次解锁符文大陆悬浮球",
    trigger: "首次完成双猜英挑战，解锁悬浮球",
    reward: { type: "card", cardId: "__fruit_bundle__", tokens: 10000 },
    hidden: false,
    status: "live",
  },
];
