// 从 card-map.json 自动生成的卡牌（共 92 张）
import { CardDef } from "./cards";

export const CUSTOM_CARDS: CardDef[] = [
  { id: "blue_2077_V", name: "V", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_V.png", upgradable: true, upgradableGroup: "cyberpunk2077" },
  { id: "blue_2077_圣剑", name: "圣剑", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_圣剑.png" },
  { id: "blue_2077_复仇者", name: "复仇者", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_复仇者.png" },
  { id: "blue_2077_多利欧", name: "多利欧", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_多利欧.png" },
  { id: "blue_2077_帕南·帕尔默", name: "帕南·帕尔默", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_帕南·帕尔默.png" },
  { id: "blue_2077_朱迪", name: "朱迪", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_朱迪.png" },
  { id: "blue_2077_法尔科", name: "法尔科", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_法尔科.png" },
  { id: "blue_2077_湖女之剑", name: "湖女之剑", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_湖女之剑.png" },
  { id: "blue_2077_琦薇", name: "琦薇", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_琦薇.png" },
  { id: "blue_2077_纳扎雷", name: "纳扎雷", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_纳扎雷.png" },
  { id: "blue_2077_草雉CT-3X", name: "草雉CT-3X", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_草雉CT-3X.png" },
  { id: "blue_2077_隼MZ2", name: "隼MZ2", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_隼MZ2.png" },
  { id: "blue_2077_老维", name: "老维", rarity: "blue", type: "cyberpunk", imageFile: "blue_2077_老维.png" },
  { id: "blue_乌迪尔_灵魂守卫", name: "灵魂守卫", rarity: "blue", type: "skin", imageFile: "blue_乌迪尔_灵魂守卫.png" },
  { id: "blue_亚托克斯_暗裔剑魔", name: "暗裔剑魔", rarity: "blue", type: "champion", imageFile: "blue_亚托克斯_暗裔剑魔.png", upgradable: true, upgradableGroup: "aatrox" },
  { id: "blue_伊芙琳_KAD", name: "KAD", rarity: "blue", type: "skin", imageFile: "blue_伊芙琳_KAD.png" },
  { id: "blue_佐伊_泳池派对", name: "泳池派对", rarity: "blue", type: "skin", imageFile: "blue_佐伊_泳池派对.png" },
  { id: "blue_佛耶戈_福牛守护者", name: "福牛守护者", rarity: "blue", type: "skin", imageFile: "blue_佛耶戈_福牛守护者.png" },
  { id: "blue_刀妹_利刃充饥", name: "利刃充饥", rarity: "blue", type: "skin", imageFile: "blue_刀妹_利刃充饥.png" },
  { id: "blue_卡兹克_奥德赛", name: "奥德赛", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_奥德赛.png" },
  { id: "blue_卡兹克_春晖海神", name: "春晖海神", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_春晖海神.png" },
  { id: "blue_卡兹克_暗星", name: "暗星", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_暗星.png" },
  { id: "blue_卡兹克_死亡绽放", name: "死亡绽放", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_死亡绽放.png" },
  { id: "blue_卡兹克_沙之守护", name: "沙之守护", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_沙之守护.png" },
  { id: "blue_卡兹克_虚空掠夺者", name: "虚空掠夺者", rarity: "blue", type: "champion", imageFile: "blue_卡兹克_虚空掠夺者.png", upgradable: true, upgradableGroup: "khazix" },
  { id: "blue_卡莎_KDA", name: "KDA", rarity: "blue", type: "skin", imageFile: "blue_卡莎_KDA.png" },
  { id: "blue_厄加特_星之守护者", name: "星之守护者", rarity: "blue", type: "skin", imageFile: "blue_厄加特_星之守护者.png" },
  { id: "blue_发条_星之守护者", name: "星之守护者", rarity: "blue", type: "skin", imageFile: "blue_发条_星之守护者.png" },
  { id: "blue_塞拉斯_幻灵战斗狼", name: "幻灵战斗狼", rarity: "blue", type: "skin", imageFile: "blue_塞拉斯_幻灵战斗狼.png" },
  { id: "blue_妮蔻_山海绘卷", name: "山海绘卷", rarity: "blue", type: "skin", imageFile: "blue_妮蔻_山海绘卷.png" },
  { id: "blue_德莱文_绿芝士", name: "绿芝士", rarity: "blue", type: "skin", imageFile: "blue_德莱文_绿芝士.png" },
  { id: "blue_斯维因_KFC", name: "KFC", rarity: "blue", type: "skin", imageFile: "blue_斯维因_KFC.png" },
  { id: "blue_最强双马尾_吕奉先", name: "吕奉先", rarity: "blue", type: "skin", imageFile: "blue_最强双马尾_吕奉先.png" },
  { id: "blue_最强室友_赵子龙", name: "赵子龙", rarity: "blue", type: "skin", imageFile: "blue_最强室友_赵子龙.png" },
  { id: "blue_格温_青蛙雨衣", name: "青蛙雨衣", rarity: "blue", type: "skin", imageFile: "blue_格温_青蛙雨衣.png" },
  { id: "blue_永恩_战斗学院", name: "战斗学院", rarity: "blue", type: "skin", imageFile: "blue_永恩_战斗学院.png" },
  { id: "blue_艾希_春晖神女", name: "春晖神女", rarity: "blue", type: "skin", imageFile: "blue_艾希_春晖神女.png" },
  { id: "blue_辛德拉_星之守护者", name: "星之守护者", rarity: "blue", type: "skin", imageFile: "blue_辛德拉_星之守护者.png" },
  { id: "blue_邓紫棋_Find You", name: "Find You", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_Find You.png" },
  { id: "blue_邓紫棋_Gloria", name: "Gloria", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_Gloria.png" },
  { id: "blue_邓紫棋_Hell 白", name: "Hell 白", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_Hell 白.png" },
  { id: "blue_邓紫棋_Hell 黑", name: "Hell 黑", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_Hell 黑.png" },
  { id: "blue_邓紫棋_你不是第一个离开的人", name: "你不是第一个离开的人", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_你不是第一个离开的人.png" },
  { id: "blue_邓紫棋_冰河时代", name: "冰河时代", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_冰河时代.png" },
  { id: "blue_邓紫棋_受难曲", name: "受难曲", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_受难曲.png" },
  { id: "blue_邓紫棋_只有我和你的地方", name: "只有我和你的地方", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_只有我和你的地方.png" },
  { id: "blue_邓紫棋_少年与海", name: "少年与海", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_少年与海.png" },
  { id: "blue_邓紫棋_老人与海", name: "老人与海", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_老人与海.png" },
  { id: "blue_邓紫棋_让世界暂停一分钟", name: "让世界暂停一分钟", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_让世界暂停一分钟.png" },
  { id: "blue_邓紫棋_金鱼嘴", name: "金鱼嘴", rarity: "blue", type: "gem", imageFile: "blue_邓紫棋_金鱼嘴.png", upgradable: true, upgradableGroup: "gem" },
  { id: "blue_阿卡丽_KDA", name: "KDA", rarity: "blue", type: "skin", imageFile: "blue_阿卡丽_KDA.png" },
  { id: "blue_阿狸_KDA", name: "KDA", rarity: "blue", type: "skin", imageFile: "blue_阿狸_KDA.png" },
  { id: "gold_2077_V", name: "V", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_V.png", upgradable: true, upgradableGroup: "cyberpunk2077" },
  { id: "gold_2077_大卫", name: "大卫", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_大卫.png" },
  { id: "gold_2077_强尼·银手", name: "强尼·银手", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_强尼·银手.png" },
  { id: "gold_2077_曼恩", name: "曼恩", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_曼恩.png" },
  { id: "gold_2077_杰克·威尔斯", name: "杰克·威尔斯", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_杰克·威尔斯.png" },
  { id: "gold_2077_露西", name: "露西", rarity: "gold", type: "cyberpunk", imageFile: "gold_2077_露西.png" },
  { id: "gold_丽桑卓_青花瓷", name: "青花瓷", rarity: "gold", type: "skin", imageFile: "gold_丽桑卓_青花瓷.png" },
  { id: "gold_亚托克斯_霸天剑魔", name: "霸天剑魔", rarity: "gold", type: "champion", imageFile: "gold_亚托克斯_霸天剑魔.png", upgradable: true, upgradableGroup: "aatrox" },
  { id: "gold_伊芙琳_KDA", name: "KDA", rarity: "gold", type: "skin", imageFile: "gold_伊芙琳_KDA.png" },
  { id: "gold_佛耶戈_EDG", name: "EDG", rarity: "gold", type: "skin", imageFile: "gold_佛耶戈_EDG.png" },
  { id: "gold_卡兹克_丛林灾厄", name: "丛林灾厄", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_丛林灾厄.png" },
  { id: "gold_卡兹克_冠军掠夺者", name: "冠军掠夺者", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_冠军掠夺者.png" },
  { id: "gold_卡兹克_凯旋圣装", name: "凯旋圣装", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_凯旋圣装.png" },
  { id: "gold_卡兹克_掠空魅影", name: "掠空魅影", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_掠空魅影.png" },
  { id: "gold_卡兹克_水晶掠夺者", name: "水晶掠夺者", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_水晶掠夺者.png" },
  { id: "gold_卡兹克_霸天异形", name: "霸天异形", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_霸天异形.png", upgradable: true, upgradableGroup: "khazix" },
  { id: "gold_卡兹克_黄金异端", name: "黄金异端", rarity: "gold", type: "champion", imageFile: "gold_卡兹克_黄金异端.png" },
  { id: "gold_卡莎_KDA", name: "KDA", rarity: "gold", type: "skin", imageFile: "gold_卡莎_KDA.png" },
  { id: "gold_德莱厄斯_灌篮高手", name: "灌篮高手", rarity: "gold", type: "skin", imageFile: "gold_德莱厄斯_灌篮高手.png" },
  { id: "gold_拉克丝_善意虚影", name: "善意虚影", rarity: "gold", type: "skin", imageFile: "gold_拉克丝_善意虚影.png" },
  { id: "gold_拉克丝_灭国魔女", name: "灭国魔女", rarity: "gold", type: "skin", imageFile: "gold_拉克丝_灭国魔女.png" },
  { id: "gold_皎月_女帝", name: "女帝", rarity: "gold", type: "skin", imageFile: "gold_皎月_女帝.png" },
  { id: "gold_莫甘娜_魔女", name: "魔女", rarity: "gold", type: "skin", imageFile: "gold_莫甘娜_魔女.png" },
  { id: "gold_萨勒芬妮_海之歌", name: "海之歌", rarity: "gold", type: "skin", imageFile: "gold_萨勒芬妮_海之歌.png" },
  { id: "gold_蔚_双城斗士", name: "双城斗士", rarity: "gold", type: "skin", imageFile: "gold_蔚_双城斗士.png" },
  { id: "gold_邓紫棋_不想回家", name: "不想回家", rarity: "gold", type: "gem", imageFile: "gold_邓紫棋_不想回家.png" },
  { id: "gold_邓紫棋_夜的尽头", name: "夜的尽头", rarity: "gold", type: "gem", imageFile: "gold_邓紫棋_夜的尽头.png" },
  { id: "gold_邓紫棋_天空没有极限", name: "天空没有极限", rarity: "gold", type: "gem", imageFile: "gold_邓紫棋_天空没有极限.png" },
  { id: "gold_邓紫棋_离心力", name: "离心力", rarity: "gold", type: "gem", imageFile: "gold_邓紫棋_离心力.png" },
  { id: "gold_邓紫棋_金鱼嘴", name: "金鱼嘴", rarity: "gold", type: "gem", imageFile: "gold_邓紫棋_金鱼嘴.png", upgradable: true, upgradableGroup: "gem" },
  { id: "gold_金克斯_破碎者", name: "破碎者", rarity: "gold", type: "skin", imageFile: "gold_金克斯_破碎者.png" },
  { id: "gold_阿卡丽_KDA", name: "KDA", rarity: "gold", type: "skin", imageFile: "gold_阿卡丽_KDA.png" },
  { id: "gold_阿狸_KDA", name: "KDA", rarity: "gold", type: "skin", imageFile: "gold_阿狸_KDA.png" },
  { id: "max_2077_V", name: "V", rarity: "ultimate", type: "cyberpunk", imageFile: "max_2077_V.png", upgradable: true, upgradableGroup: "cyberpunk2077" },
  { id: "max_2077_星河入梦", name: "星河入梦", rarity: "ultimate", type: "cyberpunk", imageFile: "max_2077_星河入梦.png" },
  { id: "max_2077_月相同轨", name: "月相同轨", rarity: "ultimate", type: "cyberpunk", imageFile: "max_2077_月相同轨.png" },
  { id: "max_亚托克斯_涤罪之翼", name: "涤罪之翼", rarity: "ultimate", type: "champion", imageFile: "max_亚托克斯_涤罪之翼.png", upgradable: true, upgradableGroup: "aatrox" },
  { id: "max_卡兹克_刹那银光", name: "刹那银光", rarity: "ultimate", type: "champion", imageFile: "max_卡兹克_刹那银光.png", upgradable: true, upgradableGroup: "khazix" },
  { id: "max_邓紫棋_启示录", name: "启示录", rarity: "ultimate", type: "gem", imageFile: "max_邓紫棋_启示录.png" },
  { id: "max_邓紫棋_金鱼嘴", name: "金鱼嘴", rarity: "ultimate", type: "gem", imageFile: "max_邓紫棋_金鱼嘴.png", upgradable: true, upgradableGroup: "gem" },
];
