// LOL 全英雄数据库 — 用于猜英雄游戏
// 维度：性别、种族、分路、地区、上线年份、攻击方式、技能消耗方式

export type Gender = "男性" | "女性" | "其他";
export type Species =
  | "人类"
  | "约德尔人"
  | "亡灵"
  | "暗裔"
  | "神灵"
  | "恶魔"
  | "虚空生物"
  | "飞升者"
  | "星灵"
  | "半神"
  | "机械"
  | "冰裔"
  | "瓦斯塔亚"
  | "龙"
  | "灵体"
  | "亡灵"
  | "巨魔"
  | "元素生物"
  | "吉祥物"
  | "改造人"
  | "蛇人"
  | "魔像"
  | "未知";
export type Lane = "上单" | "打野" | "中单" | "下路" | "辅助" | "全能";
export type Region =
  | "德玛西亚"
  | "诺克萨斯"
  | "艾欧尼亚"
  | "祖安"
  | "皮尔特沃夫"
  | "弗雷尔卓德"
  | "恕瑞玛"
  | "暗影岛"
  | "比尔吉沃特"
  | "巨神峰"
  | "班德尔城"
  | "虚空"
  | "艾卡西亚"
  | "以绪塔尔";
export type AttackType = "近战" | "远程" | "双形态";
export type ResourceType = "法力值" | "能量" | "怒气" | "生命值" | "无消耗" | "热量" | "护盾";

export interface Champion {
  id: string;
  name: string;
  aliases?: string[];
  gender: Gender;
  species: Species;
  lanes: Lane[];
  region: Region;
  releaseYear: number;
  attackType: AttackType;
  resourceType: ResourceType;
}

// 别名映射
const ALIASES: Record<string, string[]> = {
  aatrox: ["剑魔", "亚托克斯"],
  ahri: ["狐狸", "阿狸"],
  akali: ["阿卡丽"],
  akshan: ["阿克尚"],
  alistar: ["牛头", "牛"],
  amumu: ["木乃伊", "阿木木"],
  anivia: ["冰鸟", "冰晶凤凰"],
  annie: ["火女", "安妮"],
  aphelios: ["月男", "厄斐琉斯"],
  ashe: ["寒冰", "艾希"],
  aurelionsol: ["龙王", "奥瑞利安索尔"],
  azir: ["沙皇", "阿兹尔"],
  bard: ["巴德"],
  belveth: ["大卑", "卑尔维斯", "女皇"],
  blitzcrank: ["机器人", "布里茨"],
  brand: ["火男", "布兰德"],
  braum: ["布隆"],
  caitlyn: ["女警", "凯特琳"],
  camille: ["青钢影", "卡蜜尔"],
  cassiopeia: ["蛇女", "卡西奥佩娅"],
  chogath: ["大虫子", "科加斯"],
  corki: ["飞机", "库奇"],
  darius: ["诺手", "德莱厄斯"],
  diana: ["皎月", "黛安娜"],
  draven: ["德莱文"],
  drmundo: ["蒙多"],
  ekko: ["艾克"],
  elise: ["蜘蛛", "伊莉丝"],
  evelynn: ["寡妇", "伊芙琳"],
  ezreal: ["EZ", "伊泽瑞尔"],
  fiddlesticks: ["稻草人", "费德提克"],
  fiora: ["剑姬", "菲奥娜"],
  fizz: ["小鱼人", "菲兹"],
  galio: ["加里奥"],
  gangplank: ["船长", "普朗克"],
  garen: ["盖伦", "德玛西亚之力"],
  gnar: ["纳尔"],
  gragas: ["酒桶", "古拉加斯"],
  graves: ["男枪", "格雷福斯"],
  gwen: ["格温"],
  hecarim: ["人马", "赫卡里姆"],
  heimerdinger: ["大头", "黑默丁格"],
  illaoi: ["俄洛伊", "触手妈"],
  irelia: ["刀妹", "艾瑞莉娅"],
  ivern: ["艾翁", "翠神"],
  janna: ["风女", "迦娜"],
  jarvaniv: ["皇子", "嘉文四世"],
  jax: ["武器", "贾克斯"],
  jayce: ["杰斯"],
  jhin: ["烬"],
  jinx: ["金克丝"],
  kaisa: ["卡莎"],
  kalista: ["卡莉丝塔", "滑板鞋"],
  karma: ["卡尔玛", "扇子妈"],
  karthus: ["死歌", "卡尔萨斯"],
  kassadin: ["卡萨丁"],
  katarina: ["卡特", "卡特琳娜"],
  kayle: ["凯尔", "天使"],
  kayn: ["凯隐"],
  kennen: ["凯南"],
  khazix: ["螳螂", "卡兹克"],
  kindred: ["千珏"],
  kled: ["克烈"],
  kogmaw: ["大嘴", "克格莫"],
  ksante: ["奎桑提"],
  leblanc: ["妖姬", "乐芙兰"],
  leesin: ["盲僧", "李青"],
  leona: ["日女", "蕾欧娜"],
  lillia: ["莉莉娅", "小鹿"],
  lissandra: ["冰女", "丽桑卓"],
  lucian: ["卢锡安", "奥巴马"],
  lulu: ["璐璐"],
  lux: ["拉克丝", "光辉"],
  malphite: ["石头人", "墨菲特"],
  malzahar: ["蚂蚱", "玛尔扎哈"],
  maokai: ["大树", "茂凯"],
  masteryi: ["剑圣", "易大师"],
  missfortune: ["女枪", "MF", "厄运小姐"],
  mordekaiser: ["铁男", "莫德凯撒"],
  morgana: ["莫甘娜"],
  nami: ["娜美"],
  nasus: ["狗头", "内瑟斯", "沙漠死神"],
  nautilus: ["泰坦", "诺提勒斯"],
  neeko: ["妮蔻"],
  nidalee: ["豹女", "奈德丽"],
  nocturne: ["魔腾", "梦魇"],
  nunu: ["努努"],
  olaf: ["奥拉夫"],
  orianna: ["发条", "奥莉安娜"],
  ornn: ["奥恩"],
  pantheon: ["潘森", "斯巴达"],
  poppy: ["波比"],
  pyke: ["派克"],
  qiyana: ["奇亚娜"],
  quinn: ["奎因"],
  rakan: ["洛"],
  rammus: ["龙龟", "拉莫斯"],
  reksai: ["挖掘机", "雷克塞"],
  renekton: ["鳄鱼", "雷克顿"],
  rengar: ["狮子狗", "雷恩加尔"],
  riven: ["锐雯"],
  rumble: ["兰博"],
  ryze: ["瑞兹", "流浪法师"],
  samira: ["莎弥拉"],
  sejuani: ["猪妹", "瑟庄妮"],
  senna: ["赛娜"],
  seraphine: ["萨勒芬妮"],
  sett: ["腕豪", "瑟提"],
  shaco: ["小丑", "萨科"],
  shen: ["慎"],
  shyvana: ["龙女", "希瓦娜"],
  singed: ["炼金", "辛吉德"],
  sion: ["赛恩"],
  sivir: ["轮子妈", "希维尔"],
  skarner: ["蝎子", "斯卡纳"],
  sona: ["琴女", "娑娜"],
  soraka: ["奶妈", "索拉卡"],
  swain: ["乌鸦", "斯维因"],
  sylas: ["塞拉斯"],
  syndra: ["辛德拉"],
  tahmkench: ["塔姆", "蛤蟆"],
  taliyah: ["岩雀", "塔莉垭"],
  talon: ["男刀", "泰隆"],
  taric: ["塔里克", "宝石"],
  teemo: ["提莫"],
  thresh: ["锤石"],
  tristana: ["小炮", "崔丝塔娜"],
  trundle: ["巨魔", "特朗德尔"],
  tryndamere: ["蛮王", "泰达米尔"],
  twistedfate: ["卡牌", "崔斯特"],
  twitch: ["老鼠", "图奇"],
  udyr: ["乌迪尔"],
  urgot: ["厄加特", "螃蟹"],
  varus: ["韦鲁斯"],
  vayne: ["薇恩", "VN"],
  veigar: ["小法", "维迦"],
  velkoz: ["大眼", "维克兹"],
  vex: ["薇古丝"],
  vi: ["蔚"],
  viego: ["佛耶戈", "破败王"],
  viktor: ["维克托"],
  vladimir: ["吸血鬼", "弗拉基米尔"],
  volibear: ["狗熊", "沃利贝尔"],
  warwick: ["狼人", "沃里克"],
  wukong: ["猴子", "孙悟空"],
  xayah: ["霞"],
  xerath: ["泽拉斯"],
  xinzhao: ["赵信"],
  yasuo: ["亚索", "快乐风男"],
  yone: ["永恩"],
  yorick: ["约里克", "掘墓"],
  yuumi: ["悠米", "猫咪"],
  zac: ["扎克"],
  zed: ["劫"],
  zeri: ["泽丽"],
  ziggs: ["炸弹人", "吉格斯"],
  zilean: ["时光", "基兰"],
  zoe: ["佐伊"],
  zyra: ["婕拉"],
  yunara: ["芸阿娜"],
  yaheng: ["亚恒"],
};

export const champions: Champion[] = [
  // ─── A ───
  {
    id: "aatrox",
    name: "亚托克斯",
    gender: "男性",
    species: "暗裔",
    lanes: ["上单"],
    region: "恕瑞玛",
    releaseYear: 2013,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "ahri",
    name: "阿狸",
    gender: "女性",
    species: "瓦斯塔亚",
    lanes: ["中单"],
    region: "艾欧尼亚",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "akali",
    name: "阿卡丽",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "艾欧尼亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "能量",
  },
  {
    id: "akshan",
    name: "阿克尚",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "下路"],
    region: "恕瑞玛",
    releaseYear: 2021,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "alistar",
    name: "阿利斯塔",
    gender: "男性",
    species: "吉祥物",
    lanes: ["辅助"],
    region: "诺克萨斯",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "ambessa",
    name: "安蓓萨",
    gender: "女性",
    species: "人类",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2024,
    attackType: "近战",
    resourceType: "能量",
  },
  {
    id: "amumu",
    name: "阿木木",
    gender: "男性",
    species: "亡灵",
    lanes: ["打野", "辅助"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "anivia",
    name: "艾尼维亚",
    gender: "女性",
    species: "半神",
    lanes: ["中单"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "annie",
    name: "安妮",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "辅助"],
    region: "诺克萨斯",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "aphelios",
    name: "厄斐琉斯",
    gender: "男性",
    species: "人类",
    lanes: ["下路"],
    region: "巨神峰",
    releaseYear: 2019,
    attackType: "远程",
    resourceType: "无消耗",
  },
  {
    id: "ashe",
    name: "艾希",
    gender: "女性",
    species: "冰裔",
    lanes: ["下路", "辅助"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "aurelionsol",
    name: "奥瑞利安·索尔",
    gender: "男性",
    species: "龙",
    lanes: ["中单"],
    region: "巨神峰",
    releaseYear: 2016,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "aurora",
    name: "阿萝拉",
    gender: "女性",
    species: "瓦斯塔亚",
    lanes: ["中单", "上单"],
    region: "弗雷尔卓德",
    releaseYear: 2024,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "azir",
    name: "阿兹尔",
    gender: "男性",
    species: "飞升者",
    lanes: ["中单"],
    region: "恕瑞玛",
    releaseYear: 2014,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── B ───
  {
    id: "bard",
    name: "巴德",
    gender: "男性",
    species: "神灵",
    lanes: ["辅助"],
    region: "巨神峰",
    releaseYear: 2015,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "belveth",
    name: "卑尔维斯",
    gender: "女性",
    species: "虚空生物",
    lanes: ["打野"],
    region: "虚空",
    releaseYear: 2022,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "blitzcrank",
    name: "布里茨",
    gender: "其他",
    species: "机械",
    lanes: ["辅助"],
    region: "祖安",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "brand",
    name: "布兰德",
    gender: "男性",
    species: "灵体",
    lanes: ["中单", "辅助"],
    region: "弗雷尔卓德",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "braum",
    name: "布隆",
    gender: "男性",
    species: "冰裔",
    lanes: ["辅助"],
    region: "弗雷尔卓德",
    releaseYear: 2014,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "briar",
    name: "贝蕾亚",
    gender: "女性",
    species: "恶魔",
    lanes: ["打野"],
    region: "诺克萨斯",
    releaseYear: 2023,
    attackType: "近战",
    resourceType: "生命值",
  },

  // ─── C ───
  {
    id: "caitlyn",
    name: "凯特琳",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "皮尔特沃夫",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "camille",
    name: "卡蜜尔",
    gender: "女性",
    species: "改造人",
    lanes: ["上单"],
    region: "皮尔特沃夫",
    releaseYear: 2016,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "cassiopeia",
    name: "卡西奥佩娅",
    gender: "女性",
    species: "蛇人",
    lanes: ["中单"],
    region: "诺克萨斯",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "chogath",
    name: "科加斯",
    gender: "男性",
    species: "虚空生物",
    lanes: ["上单"],
    region: "虚空",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "corki",
    name: "库奇",
    gender: "男性",
    species: "约德尔人",
    lanes: ["下路", "中单"],
    region: "皮尔特沃夫",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── D ───
  {
    id: "darius",
    name: "德莱厄斯",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "diana",
    name: "黛安娜",
    gender: "女性",
    species: "星灵",
    lanes: ["中单", "打野"],
    region: "巨神峰",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "draven",
    name: "德莱文",
    gender: "男性",
    species: "人类",
    lanes: ["下路"],
    region: "诺克萨斯",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "drmundo",
    name: "蒙多医生",
    gender: "男性",
    species: "人类",
    lanes: ["上单", "打野"],
    region: "祖安",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "生命值",
  },

  // ─── E ───
  {
    id: "ekko",
    name: "艾克",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "打野"],
    region: "祖安",
    releaseYear: 2015,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "elise",
    name: "伊莉丝",
    gender: "女性",
    species: "人类",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2012,
    attackType: "双形态",
    resourceType: "法力值",
  },
  {
    id: "evelynn",
    name: "伊芙琳",
    gender: "女性",
    species: "恶魔",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "ezreal",
    name: "伊泽瑞尔",
    gender: "男性",
    species: "人类",
    lanes: ["下路"],
    region: "皮尔特沃夫",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── F ───
  {
    id: "fiddlesticks",
    name: "费德提克",
    gender: "其他",
    species: "恶魔",
    lanes: ["打野"],
    region: "德玛西亚",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "fiora",
    name: "菲奥娜",
    gender: "女性",
    species: "人类",
    lanes: ["上单"],
    region: "德玛西亚",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "fizz",
    name: "菲兹",
    gender: "男性",
    species: "约德尔人",
    lanes: ["中单"],
    region: "比尔吉沃特",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── G ───
  {
    id: "galio",
    name: "加里奥",
    gender: "其他",
    species: "魔像",
    lanes: ["中单", "辅助"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "gangplank",
    name: "普朗克",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "比尔吉沃特",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "garen",
    name: "盖伦",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "gnar",
    name: "纳尔",
    gender: "男性",
    species: "约德尔人",
    lanes: ["上单"],
    region: "弗雷尔卓德",
    releaseYear: 2014,
    attackType: "远程",
    resourceType: "怒气",
  },
  {
    id: "gragas",
    name: "古拉加斯",
    gender: "男性",
    species: "人类",
    lanes: ["上单", "打野"],
    region: "弗雷尔卓德",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "graves",
    name: "格雷福斯",
    gender: "男性",
    species: "人类",
    lanes: ["打野"],
    region: "比尔吉沃特",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "gwen",
    name: "格温",
    gender: "女性",
    species: "亡灵",
    lanes: ["上单"],
    region: "暗影岛",
    releaseYear: 2021,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── H ───
  {
    id: "hecarim",
    name: "赫卡里姆",
    gender: "男性",
    species: "亡灵",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "heimerdinger",
    name: "黑默丁格",
    gender: "男性",
    species: "约德尔人",
    lanes: ["中单", "辅助"],
    region: "皮尔特沃夫",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "hwei",
    name: "慧",
    gender: "男性",
    species: "人类",
    lanes: ["中单"],
    region: "艾欧尼亚",
    releaseYear: 2023,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── I ───
  {
    id: "illaoi",
    name: "俄洛伊",
    gender: "女性",
    species: "人类",
    lanes: ["上单"],
    region: "比尔吉沃特",
    releaseYear: 2015,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "irelia",
    name: "艾瑞莉娅",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "艾欧尼亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "ivern",
    name: "艾翁",
    gender: "男性",
    species: "神灵",
    lanes: ["打野"],
    region: "艾欧尼亚",
    releaseYear: 2016,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── J ───
  {
    id: "janna",
    name: "迦娜",
    gender: "女性",
    species: "神灵",
    lanes: ["辅助"],
    region: "皮尔特沃夫",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "jarvaniv",
    name: "嘉文四世",
    gender: "男性",
    species: "人类",
    lanes: ["打野", "上单"],
    region: "德玛西亚",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "jax",
    name: "贾克斯",
    gender: "男性",
    species: "未知",
    lanes: ["上单", "打野"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "jayce",
    name: "杰斯",
    gender: "男性",
    species: "人类",
    lanes: ["上单", "中单"],
    region: "皮尔特沃夫",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "jhin",
    name: "烬",
    gender: "男性",
    species: "人类",
    lanes: ["下路"],
    region: "艾欧尼亚",
    releaseYear: 2016,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "jinx",
    name: "金克丝",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "祖安",
    releaseYear: 2013,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── K ───
  {
    id: "kaisa",
    name: "卡莎",
    gender: "女性",
    species: "虚空生物",
    lanes: ["下路"],
    region: "虚空",
    releaseYear: 2018,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "kalista",
    name: "卡莉丝塔",
    gender: "女性",
    species: "亡灵",
    lanes: ["下路"],
    region: "暗影岛",
    releaseYear: 2014,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "karma",
    name: "卡尔玛",
    gender: "女性",
    species: "人类",
    lanes: ["辅助", "中单"],
    region: "艾欧尼亚",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "karthus",
    name: "卡尔萨斯",
    gender: "男性",
    species: "亡灵",
    lanes: ["打野", "中单"],
    region: "暗影岛",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "kassadin",
    name: "卡萨丁",
    gender: "男性",
    species: "人类",
    lanes: ["中单"],
    region: "虚空",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "katarina",
    name: "卡特琳娜",
    gender: "女性",
    species: "人类",
    lanes: ["中单"],
    region: "诺克萨斯",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "kayle",
    name: "凯尔",
    gender: "女性",
    species: "星灵",
    lanes: ["上单"],
    region: "德玛西亚",
    releaseYear: 2009,
    attackType: "双形态",
    resourceType: "法力值",
  },
  {
    id: "kayn",
    name: "凯隐",
    gender: "男性",
    species: "暗裔",
    lanes: ["打野"],
    region: "艾欧尼亚",
    releaseYear: 2017,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "kennen",
    name: "凯南",
    gender: "男性",
    species: "约德尔人",
    lanes: ["上单"],
    region: "艾欧尼亚",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "能量",
  },
  {
    id: "khazix",
    name: "卡兹克",
    gender: "男性",
    species: "虚空生物",
    lanes: ["打野"],
    region: "虚空",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "kindred",
    name: "千珏",
    gender: "其他",
    species: "神灵",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2015,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "kled",
    name: "克烈",
    gender: "男性",
    species: "约德尔人",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2016,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "kogmaw",
    name: "克格莫",
    gender: "男性",
    species: "虚空生物",
    lanes: ["下路"],
    region: "虚空",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "ksante",
    name: "奎桑提",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "恕瑞玛",
    releaseYear: 2022,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── L ───
  {
    id: "leblanc",
    name: "乐芙兰",
    gender: "女性",
    species: "人类",
    lanes: ["中单"],
    region: "诺克萨斯",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "leesin",
    name: "李青",
    gender: "男性",
    species: "人类",
    lanes: ["打野"],
    region: "艾欧尼亚",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "能量",
  },
  {
    id: "leona",
    name: "蕾欧娜",
    gender: "女性",
    species: "星灵",
    lanes: ["辅助"],
    region: "巨神峰",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "lillia",
    name: "莉莉娅",
    gender: "女性",
    species: "灵体",
    lanes: ["打野"],
    region: "艾欧尼亚",
    releaseYear: 2020,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "lissandra",
    name: "丽桑卓",
    gender: "女性",
    species: "冰裔",
    lanes: ["中单"],
    region: "弗雷尔卓德",
    releaseYear: 2013,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "lucian",
    name: "卢锡安",
    gender: "男性",
    species: "人类",
    lanes: ["下路"],
    region: "德玛西亚",
    releaseYear: 2013,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "lulu",
    name: "璐璐",
    gender: "女性",
    species: "约德尔人",
    lanes: ["辅助"],
    region: "班德尔城",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "lux",
    name: "拉克丝",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "辅助"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── M ───
  {
    id: "malphite",
    name: "墨菲特",
    gender: "男性",
    species: "元素生物",
    lanes: ["上单"],
    region: "以绪塔尔",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "malzahar",
    name: "玛尔扎哈",
    gender: "男性",
    species: "虚空生物",
    lanes: ["中单"],
    region: "虚空",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "maokai",
    name: "茂凯",
    gender: "男性",
    species: "灵体",
    lanes: ["打野", "上单"],
    region: "暗影岛",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "masteryi",
    name: "易",
    gender: "男性",
    species: "人类",
    lanes: ["打野"],
    region: "艾欧尼亚",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "milio",
    name: "米利欧",
    gender: "男性",
    species: "人类",
    lanes: ["辅助"],
    region: "以绪塔尔",
    releaseYear: 2023,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "missfortune",
    name: "厄运小姐",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "比尔吉沃特",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "mordekaiser",
    name: "莫德凯撒",
    gender: "男性",
    species: "亡灵",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "护盾",
  },
  {
    id: "morgana",
    name: "莫甘娜",
    gender: "女性",
    species: "星灵",
    lanes: ["辅助", "中单"],
    region: "德玛西亚",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "mel",
    name: "梅尔",
    gender: "女性",
    species: "人类",
    lanes: ["中单"],
    region: "诺克萨斯",
    releaseYear: 2025,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── N ───
  {
    id: "naafiri",
    name: "纳亚菲利",
    gender: "女性",
    species: "暗裔",
    lanes: ["中单", "打野"],
    region: "恕瑞玛",
    releaseYear: 2023,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "nami",
    name: "娜美",
    gender: "女性",
    species: "瓦斯塔亚",
    lanes: ["辅助"],
    region: "巨神峰",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "nasus",
    name: "内瑟斯",
    gender: "男性",
    species: "飞升者",
    lanes: ["上单"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "nautilus",
    name: "诺提勒斯",
    gender: "男性",
    species: "亡灵",
    lanes: ["辅助"],
    region: "比尔吉沃特",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "neeko",
    name: "妮蔻",
    gender: "女性",
    species: "瓦斯塔亚",
    lanes: ["中单", "辅助"],
    region: "以绪塔尔",
    releaseYear: 2018,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "nidalee",
    name: "奈德丽",
    gender: "女性",
    species: "人类",
    lanes: ["打野"],
    region: "以绪塔尔",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "nilah",
    name: "尼菈",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "比尔吉沃特",
    releaseYear: 2022,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "nocturne",
    name: "魔腾",
    gender: "男性",
    species: "恶魔",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "nunu",
    name: "努努和威朗普",
    gender: "男性",
    species: "人类",
    lanes: ["打野"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── O ───
  {
    id: "olaf",
    name: "奥拉夫",
    gender: "男性",
    species: "冰裔",
    lanes: ["上单", "打野"],
    region: "弗雷尔卓德",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "orianna",
    name: "奥莉安娜",
    gender: "女性",
    species: "机械",
    lanes: ["中单"],
    region: "皮尔特沃夫",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "ornn",
    name: "奥恩",
    gender: "男性",
    species: "半神",
    lanes: ["上单"],
    region: "弗雷尔卓德",
    releaseYear: 2017,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── P ───
  {
    id: "pantheon",
    name: "潘森",
    gender: "男性",
    species: "星灵",
    lanes: ["上单", "中单", "辅助"],
    region: "巨神峰",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "poppy",
    name: "波比",
    gender: "女性",
    species: "约德尔人",
    lanes: ["上单", "打野"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "pyke",
    name: "派克",
    gender: "男性",
    species: "亡灵",
    lanes: ["辅助"],
    region: "比尔吉沃特",
    releaseYear: 2018,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── Q ───
  {
    id: "qiyana",
    name: "奇亚娜",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "打野"],
    region: "以绪塔尔",
    releaseYear: 2019,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "quinn",
    name: "奎因",
    gender: "女性",
    species: "人类",
    lanes: ["上单", "下路"],
    region: "德玛西亚",
    releaseYear: 2013,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── R ───
  {
    id: "rakan",
    name: "洛",
    gender: "男性",
    species: "瓦斯塔亚",
    lanes: ["辅助"],
    region: "艾欧尼亚",
    releaseYear: 2017,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "rammus",
    name: "拉莫斯",
    gender: "男性",
    species: "吉祥物",
    lanes: ["打野"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "reksai",
    name: "雷克塞",
    gender: "女性",
    species: "虚空生物",
    lanes: ["打野"],
    region: "虚空",
    releaseYear: 2014,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "rell",
    name: "芮尔",
    gender: "女性",
    species: "人类",
    lanes: ["辅助"],
    region: "诺克萨斯",
    releaseYear: 2020,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "renataglasc",
    name: "烈娜塔·戈拉斯克",
    gender: "女性",
    species: "人类",
    lanes: ["辅助"],
    region: "祖安",
    releaseYear: 2022,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "renekton",
    name: "雷克顿",
    gender: "男性",
    species: "飞升者",
    lanes: ["上单"],
    region: "恕瑞玛",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "rengar",
    name: "雷恩加尔",
    gender: "男性",
    species: "瓦斯塔亚",
    lanes: ["打野"],
    region: "以绪塔尔",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "riven",
    name: "锐雯",
    gender: "女性",
    species: "人类",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "rumble",
    name: "兰博",
    gender: "男性",
    species: "约德尔人",
    lanes: ["上单"],
    region: "皮尔特沃夫",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "热量",
  },
  {
    id: "ryze",
    name: "瑞兹",
    gender: "男性",
    species: "人类",
    lanes: ["中单"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── S ───
  {
    id: "samira",
    name: "莎弥拉",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "诺克萨斯",
    releaseYear: 2020,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "sejuani",
    name: "瑟庄妮",
    gender: "女性",
    species: "冰裔",
    lanes: ["打野"],
    region: "弗雷尔卓德",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "senna",
    name: "赛娜",
    gender: "女性",
    species: "亡灵",
    lanes: ["下路", "辅助"],
    region: "暗影岛",
    releaseYear: 2019,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "seraphine",
    name: "萨勒芬妮",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "辅助"],
    region: "皮尔特沃夫",
    releaseYear: 2020,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "sett",
    name: "瑟提",
    gender: "男性",
    species: "瓦斯塔亚",
    lanes: ["上单", "辅助"],
    region: "艾欧尼亚",
    releaseYear: 2020,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "shaco",
    name: "萨科",
    gender: "男性",
    species: "灵体",
    lanes: ["打野"],
    region: "诺克萨斯",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "shen",
    name: "慎",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "艾欧尼亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "能量",
  },
  {
    id: "shyvana",
    name: "希瓦娜",
    gender: "女性",
    species: "龙",
    lanes: ["打野"],
    region: "德玛西亚",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "singed",
    name: "辛吉德",
    gender: "男性",
    species: "改造人",
    lanes: ["上单"],
    region: "祖安",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "sion",
    name: "赛恩",
    gender: "男性",
    species: "亡灵",
    lanes: ["上单"],
    region: "诺克萨斯",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "sivir",
    name: "希维尔",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "skarner",
    name: "斯卡纳",
    gender: "男性",
    species: "吉祥物",
    lanes: ["打野"],
    region: "以绪塔尔",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "smolder",
    name: "斯莫德",
    gender: "男性",
    species: "龙",
    lanes: ["下路"],
    region: "诺克萨斯",
    releaseYear: 2024,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "sona",
    name: "娑娜",
    gender: "女性",
    species: "人类",
    lanes: ["辅助"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "soraka",
    name: "索拉卡",
    gender: "女性",
    species: "神灵",
    lanes: ["辅助"],
    region: "巨神峰",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "swain",
    name: "斯维因",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "辅助"],
    region: "诺克萨斯",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "sylas",
    name: "塞拉斯",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "德玛西亚",
    releaseYear: 2019,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "syndra",
    name: "辛德拉",
    gender: "女性",
    species: "人类",
    lanes: ["中单"],
    region: "艾欧尼亚",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── T ───
  {
    id: "tahmkench",
    name: "塔姆·肯奇",
    gender: "男性",
    species: "恶魔",
    lanes: ["辅助", "上单"],
    region: "比尔吉沃特",
    releaseYear: 2015,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "taliyah",
    name: "塔莉垭",
    gender: "女性",
    species: "人类",
    lanes: ["中单", "打野"],
    region: "恕瑞玛",
    releaseYear: 2016,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "talon",
    name: "泰隆",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "打野"],
    region: "诺克萨斯",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "taric",
    name: "塔里克",
    gender: "男性",
    species: "星灵",
    lanes: ["辅助"],
    region: "巨神峰",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "teemo",
    name: "提莫",
    gender: "男性",
    species: "约德尔人",
    lanes: ["上单"],
    region: "班德尔城",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "thresh",
    name: "锤石",
    gender: "男性",
    species: "亡灵",
    lanes: ["辅助"],
    region: "暗影岛",
    releaseYear: 2013,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "tristana",
    name: "崔丝塔娜",
    gender: "女性",
    species: "约德尔人",
    lanes: ["下路"],
    region: "班德尔城",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "trundle",
    name: "特朗德尔",
    gender: "男性",
    species: "巨魔",
    lanes: ["上单", "打野"],
    region: "弗雷尔卓德",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "tryndamere",
    name: "泰达米尔",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "怒气",
  },
  {
    id: "twistedfate",
    name: "崔斯特",
    gender: "男性",
    species: "人类",
    lanes: ["中单"],
    region: "比尔吉沃特",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "twitch",
    name: "图奇",
    gender: "男性",
    species: "未知",
    lanes: ["下路"],
    region: "祖安",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── U ───
  {
    id: "udyr",
    name: "乌迪尔",
    gender: "男性",
    species: "人类",
    lanes: ["打野", "上单"],
    region: "弗雷尔卓德",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "urgot",
    name: "厄加特",
    gender: "男性",
    species: "机械",
    lanes: ["上单"],
    region: "祖安",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── V ───
  {
    id: "varus",
    name: "韦鲁斯",
    gender: "男性",
    species: "暗裔",
    lanes: ["下路"],
    region: "恕瑞玛",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "vayne",
    name: "薇恩",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "德玛西亚",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "veigar",
    name: "维迦",
    gender: "男性",
    species: "约德尔人",
    lanes: ["中单"],
    region: "班德尔城",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "velkoz",
    name: "维克兹",
    gender: "男性",
    species: "虚空生物",
    lanes: ["中单", "辅助"],
    region: "虚空",
    releaseYear: 2014,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "vex",
    name: "薇古丝",
    gender: "女性",
    species: "约德尔人",
    lanes: ["中单"],
    region: "暗影岛",
    releaseYear: 2021,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "vi",
    name: "蔚",
    gender: "女性",
    species: "人类",
    lanes: ["打野"],
    region: "皮尔特沃夫",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "viego",
    name: "佛耶戈",
    gender: "男性",
    species: "亡灵",
    lanes: ["打野"],
    region: "暗影岛",
    releaseYear: 2021,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "viktor",
    name: "维克托",
    gender: "男性",
    species: "机械",
    lanes: ["中单"],
    region: "祖安",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "vladimir",
    name: "弗拉基米尔",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "诺克萨斯",
    releaseYear: 2010,
    attackType: "远程",
    resourceType: "生命值",
  },
  {
    id: "volibear",
    name: "沃利贝尔",
    gender: "男性",
    species: "半神",
    lanes: ["上单", "打野"],
    region: "弗雷尔卓德",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── W ───
  {
    id: "warwick",
    name: "沃里克",
    gender: "男性",
    species: "机械",
    lanes: ["打野", "上单"],
    region: "祖安",
    releaseYear: 2009,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "wukong",
    name: "孙悟空",
    gender: "男性",
    species: "瓦斯塔亚",
    lanes: ["上单", "打野"],
    region: "艾欧尼亚",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── X ───
  {
    id: "xayah",
    name: "霞",
    gender: "女性",
    species: "瓦斯塔亚",
    lanes: ["下路"],
    region: "艾欧尼亚",
    releaseYear: 2017,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "xerath",
    name: "泽拉斯",
    gender: "男性",
    species: "飞升者",
    lanes: ["中单", "辅助"],
    region: "恕瑞玛",
    releaseYear: 2011,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "xinzhao",
    name: "赵信",
    gender: "男性",
    species: "人类",
    lanes: ["打野"],
    region: "德玛西亚",
    releaseYear: 2010,
    attackType: "近战",
    resourceType: "法力值",
  },

  // ─── Y ───
  {
    id: "yasuo",
    name: "亚索",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "艾欧尼亚",
    releaseYear: 2013,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "yone",
    name: "永恩",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "上单"],
    region: "艾欧尼亚",
    releaseYear: 2020,
    attackType: "近战",
    resourceType: "无消耗",
  },
  {
    id: "yorick",
    name: "约里克",
    gender: "男性",
    species: "人类",
    lanes: ["上单"],
    region: "暗影岛",
    releaseYear: 2011,
    attackType: "近战",
    resourceType: "法力值",
  },
  {
    id: "yuumi",
    name: "悠米",
    gender: "女性",
    species: "灵体",
    lanes: ["辅助"],
    region: "班德尔城",
    releaseYear: 2019,
    attackType: "远程",
    resourceType: "法力值",
  },

  // ─── Z ───
  {
    id: "zac",
    name: "扎克",
    gender: "男性",
    species: "元素生物",
    lanes: ["打野", "上单"],
    region: "祖安",
    releaseYear: 2013,
    attackType: "近战",
    resourceType: "生命值",
  },
  {
    id: "zed",
    name: "劫",
    gender: "男性",
    species: "人类",
    lanes: ["中单"],
    region: "艾欧尼亚",
    releaseYear: 2012,
    attackType: "近战",
    resourceType: "能量",
  },
  {
    id: "zeri",
    name: "泽丽",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "祖安",
    releaseYear: 2022,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "ziggs",
    name: "吉格斯",
    gender: "男性",
    species: "约德尔人",
    lanes: ["中单", "下路"],
    region: "祖安",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "zilean",
    name: "基兰",
    gender: "男性",
    species: "人类",
    lanes: ["中单", "辅助"],
    region: "恕瑞玛",
    releaseYear: 2009,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "zoe",
    name: "佐伊",
    gender: "女性",
    species: "星灵",
    lanes: ["中单"],
    region: "巨神峰",
    releaseYear: 2017,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "zyra",
    name: "婕拉",
    gender: "女性",
    species: "元素生物",
    lanes: ["中单", "辅助"],
    region: "以绪塔尔",
    releaseYear: 2012,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "yunara",
    name: "芸阿娜",
    gender: "女性",
    species: "人类",
    lanes: ["下路"],
    region: "艾欧尼亚",
    releaseYear: 2025,
    attackType: "远程",
    resourceType: "法力值",
  },
  {
    id: "yaheng",
    name: "亚恒",
    gender: "男性",
    species: "暗裔",
    lanes: ["上单"],
    region: "德玛西亚",
    releaseYear: 2025,
    attackType: "近战",
    resourceType: "法力值",
  },
];

// 工具函数：获取每日谜底（基于日期，同一天所有人看到同一个谜底）
export function getDailyHero(): Champion {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) /
      86400000
  );
  return champions[dayOfYear % champions.length];
}

// 工具函数：获取个人化每日谜底（基于日期 + 种子偏移）
export function getPersonalDailyHero(seed: string): Champion {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) /
      86400000
  );
  // 简单哈希
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash * 31 + seed.charCodeAt(i)) & 0xfffffff;
  }
  const index = (dayOfYear + hash) % champions.length;
  return champions[index];
}

// 7维对比
export type MatchLevel = "full" | "partial" | "none";

export interface GuessResult {
  dimension: string;
  label: string;
  guessValue: string;
  answerValue: string;
  matchLevel: MatchLevel;
}

export function compareGuess(guess: Champion, answer: Champion): GuessResult[] {
  const laneOverlap = guess.lanes.filter(l => answer.lanes.includes(l));
  const laneFullMatch = guess.lanes.length === answer.lanes.length && laneOverlap.length === guess.lanes.length;

  return [
    {
      dimension: "gender", label: "性别",
      guessValue: guess.gender, answerValue: answer.gender,
      matchLevel: guess.gender === answer.gender ? "full" : "none",
    },
    {
      dimension: "species", label: "种族",
      guessValue: guess.species, answerValue: answer.species,
      matchLevel: guess.species === answer.species ? "full" : "none",
    },
    {
      dimension: "lanes", label: "分路",
      guessValue: guess.lanes.join("/"), answerValue: answer.lanes.join("/"),
      matchLevel: laneFullMatch ? "full" : laneOverlap.length > 0 ? "partial" : "none",
    },
    {
      dimension: "region", label: "地区",
      guessValue: guess.region, answerValue: answer.region,
      matchLevel: guess.region === answer.region ? "full" : "none",
    },
    {
      dimension: "releaseYear", label: "上线年份",
      guessValue: String(guess.releaseYear), answerValue: String(answer.releaseYear),
      matchLevel: guess.releaseYear === answer.releaseYear ? "full" : "none",
    },
    {
      dimension: "attackType", label: "攻击方式",
      guessValue: guess.attackType, answerValue: answer.attackType,
      matchLevel:
        guess.attackType === answer.attackType ? "full" :
        (guess.attackType === "双形态" || answer.attackType === "双形态") ? "partial" : "none",
    },
    {
      dimension: "resourceType", label: "技能消耗",
      guessValue: guess.resourceType, answerValue: answer.resourceType,
      matchLevel: guess.resourceType === answer.resourceType ? "full" : "none",
    },
  ];
}

// 搜索英雄（名称 + ID + 别名）
export function searchChampions(query: string): Champion[] {
  const q = query.toLowerCase();
  return champions.filter(
    (c) => {
      if (c.name.includes(q) || c.id.toLowerCase().includes(q)) return true;
      const aliases = ALIASES[c.id];
      return aliases && aliases.some(a => a.toLowerCase().includes(q));
    }
  );
}
